In [32]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [3]:
df=pd.read_csv("D:/vishal7029/auto-mpg.csv")
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [21]:
#Replace '?' With nan
df.replace('?',np.nan,inplace=True)

In [22]:
#Convert Horesepower to numeric
df['horsepower']=pd.to_numeric(df['horsepower'])

In [23]:
#drop Missing values
df=df.dropna()

In [24]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130.0,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,1,ford torino

In [25]:
#remove Non Numberic Column
if 'car name' in df.columns:
  df=df.drop(columns=['car name'])

In [26]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
dtype: int64

# 2 Define Features And target

In [28]:

X=df.drop(columns=['mpg'])
y=df['mpg']

In [29]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [30]:
X_train,X_test,y_train,y_test.head()

(     cylinders  displacement  horsepower  weight  acceleration  model year  \
 260          6         225.0       110.0    3620          18.7          78
 184          4         140.0        92.0    2572          14.9          76
 174          6         171.0        97.0    2984          14.5          75
 64           8         318.0       150.0    4135          13.5          72
 344          4          86.0        64.0    1875          16.4          81
 ..         ...           ...         ...     ...           ...         ...
 72           8         304.0       150.0    3892          12.5          72
 107          6         232.0       100.0    2789          15.0          73
 272          4         151.0        85.0    2855          17.6          78
 352          4          98.0        65.0    2380          20.7          81
 103          8         400.0       150.0    4997          14.0          73

      origin
 260       1
 184       1
 174       1
 64        1
 344       1
 ..      ...
 72        1
 107       1
 272       1
 352       1
 103       1

 [313 rows x 7 columns],
      cylinders  displacement  horsepower  weight  acceleration  model year  \
 79           4          96.0        69.0    2189          18.0          72
 276          4         121.0       115.0    2795          15.7          78
 248          4          91.0        60.0    1800          16.4          78
 56           4          91.0        70.0    1955          20.5          71
 393          4         140.0        86.0    2790          15.6          82
 ..         ...           ...         ...     ...           ...         ...
 366          6         225.0        85.0    3465          16.6          81
 83           4          98.0        80.0    2164          15.0          72
 115          8         350.0       145.0    4082          13.0          73
 3            8         304.0       150.0    3433          12.0          70
 18           4          97.0        88.0    2130          14.5          70

      origin
 79        2
 276       2
 248       3
 56        1
 393       1
 ..      ...
 366       1
 83        1
 115       1
 3         1
 18        3

 [79 rows x 7 columns],
 260    18.6
 184    25.0
 174    18.0
 64     15.0
 344    39.0
        ...
 72     15.0
 107    18.0
 272    23.8
 352    29.9
 103    11.0
 Name: mpg, Length: 313, dtype: float64,
 79     26.0
 276    21.6
 248    36.1
 56     26.0
 393    27.0
 Name: mpg, dtype: float64)

# 3 Backward Feature Selection

In [33]:
selected_featured=list(X.columns)

#train full model First
model=LinearRegression()
model.fit(X_train[selected_featured],y_train)
y_pred=model.predict(X_test[selected_featured])
best_score=r2_score(y_test,y_pred)

print("backword Feature Elimination Process:\n")
print(f"Initial R2 score (all Features): {best_score:.4f}")

backword Feature Elimination Process:

Initial R2 score (all Features): 0.7902

In [34]:
while len(selected_featured) > 1:
    scores = []

    for feature in selected_featured:
        features_to_test = selected_featured.copy()
        features_to_test.remove(feature)

        model = LinearRegression()
        model.fit(X_train[features_to_test], y_train)

        y_pred = model.predict(X_test[features_to_test])
        score = r2_score(y_test, y_pred)

        scores.append((score, feature))   # Only once

    # Find removal that gives highest R2
    scores.sort(reverse=True)
    current_best_score, worst_feature = scores[0]

    if current_best_score >= best_score:
        best_score = current_best_score
        selected_featured.remove(worst_feature)
        print(f"Removed Feature: {worst_feature}, R2 score: {best_score:.4f}")
    else:
        break

print("\nFinal Selected Features:")
print(selected_featured)

Removed Feature: origin, R2 score: 0.7942
Removed Feature: horsepower, R2 score: 0.7944

Final Selected Features:
['cylinders', 'displacement', 'weight', 'acceleration', 'model year']