In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier

In [3]:
df=pd.read_csv("D:/vishal7029/auto-mpg.csv")
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [4]:
feat_labels=df.columns[1:]

In [5]:
feat_labels

Index(['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration',
       'model year', 'origin', 'car name'],
      dtype='object')

In [6]:
X, y = df.iloc[:, 1:].values, df.iloc[:, 0].values

In [7]:
X

array([[8, 307.0, '130', ..., 70, 1, 'chevrolet chevelle malibu'],
       [8, 350.0, '165', ..., 70, 1, 'buick skylark 320'],
       [8, 318.0, '150', ..., 70, 1, 'plymouth satellite'],
       ...,
       [4, 135.0, '84', ..., 82, 1, 'dodge rampage'],
       [4, 120.0, '79', ..., 82, 1, 'ford ranger'],
       [4, 119.0, '82', ..., 82, 1, 'chevy s-10']], dtype=object)

In [10]:
df.replace('?', np.nan, inplace=True)

In [11]:
X = df.drop(columns=['mpg', 'car name'])
y = df['mpg']

In [13]:
X.head()

,cylinders,displacement,horsepower,weight,acceleration,model year,origin
0,8,307.0,130,3504,12.0,70,1
1,8,350.0,165,3693,11.5,70,1
2,8,318.0,150,3436,11.0,70,1
3,8,304.0,150,3433,12.0,70,1
4,8,302.0,140,3449,10.5,70,1

In [14]:
y.head()

0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
Name: mpg, dtype: float64

In [15]:
# Split The Dataser into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [16]:
X_train, X_test, y_train, y_test.head()

(     cylinders  displacement horsepower  weight  acceleration  model year  \
 3            8         304.0        150    3433          12.0          70
 18           4          97.0         88    2130          14.5          70
 376          4          91.0         68    2025          18.2          82
 248          4          91.0         60    1800          16.4          78
 177          4         115.0         95    2694          15.0          75
 ..         ...           ...        ...     ...           ...         ...
 71           3          70.0         97    2330          13.5          72
 106          8         350.0        180    4499          12.5          73
 270          4         134.0         95    2515          14.8          78
 348          4          89.0         62    2050          17.3          81
 102          4          97.0         46    1950          21.0          73

      origin
 3         1
 18        3
 376       3
 248       3
 177       2
 ..      ...
 71        3
 106       1
 270       3
 348       3
 102       2

 [318 rows x 7 columns],
      cylinders  displacement horsepower  weight  acceleration  model year  \
 198          4          91.0         53    1795          17.4          76
 396          4         120.0         79    2625          18.6          82
 33           6         232.0        100    2634          13.0          71
 208          8         318.0        150    3940          13.2          76
 93           8         318.0        150    4237          14.5          73
 ..         ...           ...        ...     ...           ...         ...
 249          8         260.0        110    3365          15.5          78
 225          6         250.0        110    3520          16.4          77
 367          4         112.0         88    2605          19.6          82
 175          4          90.0         70    1937          14.0          75
 285          8         305.0        130    3840          15.4          79

      origin
 198       3
 396       1
 33        1
 208       1
 93        1
 ..      ...
 249       1
 225       1
 367       1
 175       2
 285       1

 [80 rows x 7 columns],
 3      16.0
 18     27.0
 376    37.0
 248    36.1
 177    23.0
        ...
 71     19.0
 106    12.0
 270    21.1
 348    37.7
 102    26.0
 Name: mpg, Length: 318, dtype: float64,
 198    33.0
 396    28.0
 33     19.0
 208    13.0
 93     14.0
 Name: mpg, dtype: float64)

In [17]:
#Create A Decision Tree Classifier
clf = DecisionTreeRegressor(random_state=42)

In [18]:
# Fit the Classifier to The training Data
clf.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

In [19]:
#Get Feature importance
feature_importances = clf.feature_importances_

In [20]:
# print featues Importnce wise
for feature, importance in zip(df.columns, feature_importances):
    print(f"{feature}: {importance}")

indices = np.argsort(feature_importances)[::-1]
for f in range(X_train.shape[1]):print("%2d) %-*s %f" % (f + 1, 30,feat_labels[f],feature_importances[indices[f]]))

mpg: 0.005163359113512224
cylinders: 0.6097119078702474
displacement: 0.17971958009996866
horsepower: 0.07097939185772395
weight: 0.018895844421352025
acceleration: 0.1131616004534618
model year: 0.0023683161837339743
 1) cylinders                      0.609712
 2) displacement                   0.179720
 3) horsepower                     0.113162
 4) weight                         0.070979
 5) acceleration                   0.018896
 6) model year                     0.005163
 7) origin                         0.002368